/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gamettt;

import java.awt.Color;
import java.awt.Container;
import javax.swing.JOptionPane;

/**
 *
 * @author Sounak
 */
public class TicTacToeGUI extends javax.swing.JFrame {

    /**
     * Creates new form TicTacToeGUI
     */
    minimax_algorithm ob;
    int turn;
    boolean isAI;
    public TicTacToeGUI() {
        initComponents();
        ob=new minimax_algorithm();
        isAI=true;
        turn = 1;
    }
    
    public TicTacToeGUI(boolean isAI, int turn)  {
        initComponents();
        ob=new minimax_algorithm();
        this.isAI=isAI;
        this.turn = turn;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        heading = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        Pos02 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        Pos01 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        Pos00 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        Pos10 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        Pos11 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        Pos12 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        Pos20 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        Pos21 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        Pos22 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Souank's TicTacToe");
        setBackground(new java.awt.Color(0, 0, 255));
        setForeground(new java.awt.Color(255, 0, 51));

        heading.setFont(new java.awt.Font("French Script MT", 0, 54)); // NOI18N
        heading.setText("  Tic Tac Toe");

        jPanel1.setBackground(new java.awt.Color(51, 153, 255));
        jPanel1.setForeground(new java.awt.Color(102, 102, 102));

        Pos02.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Pos02MouseClicked(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Calibri", 0, 48)); // NOI18N

        javax.swing.GroupLayout Pos02Layout = new javax.swing.GroupLayout(Pos02);
        Pos02.setLayout(Pos02Layout);
        Pos02Layout.setHorizontalGroup(
            Pos02Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(Pos02Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(Pos02Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 142, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        Pos02Layout.setVerticalGroup(
            Pos02Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 131, Short.MAX_VALUE)
            .addGroup(Pos02Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(Pos02Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE)))
        );

        jLabel3.setHorizontalAlignment(0);
        jLabel3.setVerticalAlignment(0);

        Pos01.setMinimumSize(new java.awt.Dimension(0, 0));
        Pos01.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Pos01MouseClicked(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Calibri", 0, 48)); // NOI18N

        javax.swing.GroupLayout Pos01Layout = new javax.swing.GroupLayout(Pos01);
        Pos01.setLayout(Pos01Layout);
        Pos01Layout.setHorizontalGroup(
            Pos01Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 102, Short.MAX_VALUE)
            .addGroup(Pos01Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(Pos01Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        Pos01Layout.setVerticalGroup(
            Pos01Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 131, Short.MAX_VALUE)
            .addGroup(Pos01Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(Pos01Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        jLabel2.setHorizontalAlignment(0);
        jLabel2.setVerticalAlignment(0);

        Pos00.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Pos00MouseClicked(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Calibri", 0, 48)); // NOI18N

        javax.swing.GroupLayout Pos00Layout = new javax.swing.GroupLayout(Pos00);
        Pos00.setLayout(Pos00Layout);
        Pos00Layout.setHorizontalGroup(
            Pos00Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(Pos00Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Pos00Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, 144, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        Pos00Layout.setVerticalGroup(
            Pos00Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(Pos00Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Pos00Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        jLabel10.setHorizontalAlignment(0);
        jLabel10.setVerticalAlignment(0);

        Pos10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Pos10MouseClicked(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Calibri", 0, 48)); // NOI18N

        javax.swing.GroupLayout Pos10Layout = new javax.swing.GroupLayout(Pos10);
        Pos10.setLayout(Pos10Layout);
        Pos10Layout.setHorizontalGroup(
            Pos10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(Pos10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Pos10Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 144, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        Pos10Layout.setVerticalGroup(
            Pos10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(Pos10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Pos10Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        jLabel4.setHorizontalAlignment(0);
        jLabel4.setVerticalAlignment(0);

        Pos11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Pos11MouseClicked(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Calibri", 0, 48)); // NOI18N

        javax.swing.GroupLayout Pos11Layout = new javax.swing.GroupLayout(Pos11);
        Pos11.setLayout(Pos11Layout);
        Pos11Layout.setHorizontalGroup(
            Pos11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 102, Short.MAX_VALUE)
            .addGroup(Pos11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(Pos11Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        Pos11Layout.setVerticalGroup(
            Pos11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 112, Short.MAX_VALUE)
            .addGroup(Pos11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(Pos11Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        jLabel5.setHorizontalAlignment(0);
        jLabel5.setVerticalAlignment(0);

        Pos12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Pos12MouseClicked(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Calibri", 0, 48)); // NOI18N

        javax.swing.GroupLayout Pos12Layout = new javax.swing.GroupLayout(Pos12);
        Pos12.setLayout(Pos12Layout);
        Pos12Layout.setHorizontalGroup(
            Pos12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(Pos12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Pos12Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 142, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        Pos12Layout.setVerticalGroup(
            Pos12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(Pos12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Pos12Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        jLabel6.setHorizontalAlignment(0);
        jLabel6.setVerticalAlignment(0);

        Pos20.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Pos20MouseClicked(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Calibri", 0, 48)); // NOI18N

        javax.swing.GroupLayout Pos20Layout = new javax.swing.GroupLayout(Pos20);
        Pos20.setLayout(Pos20Layout);
        Pos20Layout.setHorizontalGroup(
            Pos20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 156, Short.MAX_VALUE)
            .addGroup(Pos20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(Pos20Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 144, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        Pos20Layout.setVerticalGroup(
            Pos20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 135, Short.MAX_VALUE)
            .addGroup(Pos20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(Pos20Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 123, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        jLabel7.setHorizontalAlignment(0);
        jLabel7.setVerticalAlignment(0);

        Pos21.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Pos21MouseClicked(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Calibri", 0, 48)); // NOI18N

        javax.swing.GroupLayout Pos21Layout = new javax.swing.GroupLayout(Pos21);
        Pos21.setLayout(Pos21Layout);
        Pos21Layout.setHorizontalGroup(
            Pos21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 102, Short.MAX_VALUE)
            .addGroup(Pos21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(Pos21Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        Pos21Layout.setVerticalGroup(
            Pos21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(Pos21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(Pos21Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 123, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        jLabel8.setHorizontalAlignment(0);
        jLabel8.setVerticalAlignment(0);

        Pos22.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Pos22MouseClicked(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Calibri", 0, 48)); // NOI18N

        javax.swing.GroupLayout Pos22Layout = new javax.swing.GroupLayout(Pos22);
        Pos22.setLayout(Pos22Layout);
        Pos22Layout.setHorizontalGroup(
            Pos22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 154, Short.MAX_VALUE)
            .addGroup(Pos22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(Pos22Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE)))
        );
        Pos22Layout.setVerticalGroup(
            Pos22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(Pos22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(Pos22Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 123, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        jLabel9.setHorizontalAlignment(0);
        jLabel9.setVerticalAlignment(0);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(Pos20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Pos21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Pos22, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(Pos00, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Pos01, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Pos02, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(Pos10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Pos11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Pos12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Pos00, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Pos01, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Pos02, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Pos12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Pos10, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Pos11, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Pos20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Pos21, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Pos22, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(105, 105, 105))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(heading, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(67, 67, 67))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(heading, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 397, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        heading.setHorizontalAlignment(0);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void Pos00MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Pos00MouseClicked
        // TODO add your handling code here:
        mainLogic(new Move(0, 0));
    }//GEN-LAST:event_Pos00MouseClicked

    private void Pos01MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Pos01MouseClicked
        // TODO add your handling code here:
         mainLogic(new Move(0, 1));
    }//GEN-LAST:event_Pos01MouseClicked

    private void Pos02MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Pos02MouseClicked
        // TODO add your handling code here:
         mainLogic(new Move(0, 2));
    }//GEN-LAST:event_Pos02MouseClicked

    private void Pos10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Pos10MouseClicked
        // TODO add your handling code here:
         mainLogic(new Move(1, 0));
    }//GEN-LAST:event_Pos10MouseClicked

    private void Pos11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Pos11MouseClicked
        // TODO add your handling code here:
         mainLogic(new Move(1, 1));
    }//GEN-LAST:event_Pos11MouseClicked

    private void Pos12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Pos12MouseClicked
        // TODO add your handling code here:
         mainLogic(new Move(1, 2));
    }//GEN-LAST:event_Pos12MouseClicked

    private void Pos20MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Pos20MouseClicked
        // TODO add your handling code here:
         mainLogic(new Move(2, 0));
    }//GEN-LAST:event_Pos20MouseClicked

    private void Pos21MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Pos21MouseClicked
        // TODO add your handling code here:
         mainLogic(new Move(2, 1));
    }//GEN-LAST:event_Pos21MouseClicked

    private void Pos22MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Pos22MouseClicked
        // TODO add your handling code here:
         mainLogic(new Move(2, 2));
    }//GEN-LAST:event_Pos22MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TicTacToeGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TicTacToeGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TicTacToeGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TicTacToeGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TicTacToeGUI().setVisible(true);
            }
        });
    }
    
    private void mainLogic(Move currMove) {
        if(isAI){
            if(!checkValid(currMove)) {
                return;
            }
            updateEnvironment();
            if(!ob.isMovesLeft()) return;
            Move ai = getAILogic();
            checkValid(ai);
            updateEnvironment();
        }else {
            if(!checkValid(currMove))
                return;
            updateEnvironment();
        }
    }
    
    private Move getAILogic(){
        Move bestMove=ob.findBestMove();
        return bestMove;        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Pos00;
    private javax.swing.JPanel Pos01;
    private javax.swing.JPanel Pos02;
    private javax.swing.JPanel Pos10;
    private javax.swing.JPanel Pos11;
    private javax.swing.JPanel Pos12;
    private javax.swing.JPanel Pos20;
    private javax.swing.JPanel Pos21;
    private javax.swing.JPanel Pos22;
    private javax.swing.JLabel heading;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

    private boolean checkValid(Move bestMove) {
        if(ob.board[bestMove.row][bestMove.col]!='_')return false;
        if(turn == 1)
            ob.board[bestMove.row][bestMove.col]='o';
        else 
            ob.board[bestMove.row][bestMove.col]='x';
        turn=(turn)%2+1;
        return true;
        //throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    private void updateEnvironment() {
        if(ob.board[0][0]!='_')
            jLabel10.setText((ob.board[0][0]+""));
        if(ob.board[0][1]!='_')
            jLabel2.setText((ob.board[0][1]+""));
        if(ob.board[0][2]!='_')
            jLabel3.setText((ob.board[0][2]+""));
        if(ob.board[1][0]!='_')
            jLabel4.setText((ob.board[1][0]+""));
        if(ob.board[1][1]!='_')
            jLabel5.setText((ob.board[1][1]+""));
        if(ob.board[1][2]!='_')
            jLabel6.setText((ob.board[1][2]+""));
        if(ob.board[2][0]!='_')
            jLabel7.setText((ob.board[2][0]+""));
        if(ob.board[2][1]!='_')
            jLabel8.setText((ob.board[2][1]+""));
        if(ob.board[2][2]!='_')
            jLabel9.setText((ob.board[2][2]+""));
        if(isAI){
            heading.setText((turn==1? "Your Move": "AI's Move"));
            int s = ob.evaluate();
            if(s==10) JOptionPane.showMessageDialog(this, "AI wins");
            else if(s==-10) JOptionPane.showMessageDialog(this, "Player wins");
            ob.display();
            if(s!=0 || !ob.isMovesLeft()) {
                if(!ob.isMovesLeft()) JOptionPane.showMessageDialog(this, "Draw"); 
                this.dispose();
            }
        }else{
            heading.setText((turn==1? "Player 1's Move": "Player 2's Move"));
            int s = ob.evaluate();
            if(s==10) JOptionPane.showMessageDialog(this, "Player 1 wins");
            else if(s==-10) JOptionPane.showMessageDialog(this, "Player 2 wins");
            ob.display();
            if(s!=0 || !ob.isMovesLeft()) {
                if(!ob.isMovesLeft()) JOptionPane.showMessageDialog(this, "Draw"); 
                this.dispose();
            }
        }
//throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
